# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Database-Schema-Config
version:      .02
version_from: lib/Database/Schema/Config.pm
installdirs:  site
requires:
    Class::ParmList:               1.05
    Time::Timestamp:               1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
